### ISSUE TITLE
SAMBA for Forex prediction

### ISSUE THREAD

**Issue by ericleonardo** [Ali-Meh619/SAMBA#1]
Hi! Please, can you share the code?
I would like to experiment SAMBA for Forex currencies prediction.
Also, please how can SAMBA be modified to classification (up/down) for trend prediction?

Congratulations for the work! Thank you

**Comment by Ali-Meh619** [comment]
Hello,
Thank you for your message.
The code is released. You can use that.
To use that for classification, you need to modify the loss function and final layer architecture.

Thanks,
Ali
